# Generated by Django 4.1.4 on 2023-02-24 04:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities',
            name='amenity_icon',
            field=models.ImageField(upload_to='icons/amenities', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
    ]
