# Generated by Django 4.1.4 on 2023-02-24 04:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_amenities_amenity_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities',
            name='amenity_icon',
            field=models.FileField(upload_to='icons/amenities', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg'])]),
        ),
    ]
