# Generated by Django 4.1.4 on 2023-02-24 06:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_amenities_amenity_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities',
            name='amenity_icon',
            field=models.FileField(upload_to='icons/amenities', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('num_bedrooms', models.IntegerField()),
                ('num_bathrooms', models.IntegerField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=8)),
                ('main_image', models.ImageField(upload_to='images/cottage/main-images')),
                ('amenities', models.ManyToManyField(to='listings.amenities')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.host')),
            ],
        ),
    ]
