# Generated by Django 4.1.4 on 2023-02-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_amenities_amenity_icon_listings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('cottage', 'Cottage'), ('treehouse', 'Treehouse'), ('homestay', 'Homestay'), ('a-frame', 'A-Frame'), ('camp', 'Camping'), ('dome', 'Domes'), ('mudhosue', 'Mudhouse')], max_length=10)),
            ],
        ),
    ]
