# Generated by Django 4.1.4 on 2023-02-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listingtype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListingType',
        ),
        migrations.AddField(
            model_name='host',
            name='type',
            field=models.CharField(choices=[('cottage', 'Cottage'), ('treehouse', 'Treehouse'), ('homestay', 'Homestay'), ('a-frame', 'A-Frame'), ('camp', 'Camping'), ('dome', 'Domes'), ('mudhosue', 'Mudhouse')], default='hi', max_length=10),
        ),
    ]
