# Generated by Django 4.1.4 on 2023-02-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_delete_listingtype_host_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='type',
        ),
        migrations.AddField(
            model_name='listings',
            name='listing_type',
            field=models.CharField(choices=[('cottage', 'Cottage'), ('treehouse', 'Treehouse'), ('homestay', 'Homestay'), ('a-frame', 'A-Frame'), ('camp', 'Camping'), ('dome', 'Domes'), ('mudhosue', 'Mudhouse')], default='hi', max_length=10),
        ),
    ]
