# Generated by Django 4.1.4 on 2023-02-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_remove_host_type_listings_listing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='location_type',
            field=models.CharField(choices=[('roadside', 'Roadside'), ('uphill', 'Uphill'), ('downhill', 'Downhill'), ('offroad', 'Offroad')], default='roadside', max_length=10),
        ),
    ]
