# Generated by Django 4.1.4 on 2023-03-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_listings_location_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='slug',
            field=models.SlugField(default='hi'),
        ),
    ]
