# Generated by Django 4.1.4 on 2023-03-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_listings_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
