# Generated by Django 4.1.4 on 2023-03-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_photogallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photogallery',
            name='image',
            field=models.ImageField(blank=True, upload_to='photo_gallery/'),
        ),
    ]
