# Generated by Django 4.1.4 on 2023-03-14 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_remove_listings_main_image_listings_distance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='distance',
            new_name='distance_in_meters',
        ),
    ]
