# Generated by Django 4.1.4 on 2023-03-24 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_places_alter_listings_thingstoknow'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Places',
            new_name='NearByPlaces',
        ),
    ]
