# Generated by Django 4.1.4 on 2023-03-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_rename_places_nearbyplaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearbyplaces',
            name='thumb_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/places/'),
        ),
    ]
