# Generated by Django 4.1.4 on 2023-03-24 05:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_nearbyplaces_thumb_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearbyplaces',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
