# Generated by Django 4.1.4 on 2023-03-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_nearbyplaces_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearbyplaces',
            name='latitude',
            field=models.DecimalField(decimal_places=16, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='nearbyplaces',
            name='longitude',
            field=models.DecimalField(decimal_places=16, default=0, max_digits=30),
        ),
    ]
