# Generated by Django 4.1.4 on 2023-03-24 10:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_nearbyplaces_latitude_nearbyplaces_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearbyplaces',
            name='other_info',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
