# Generated by Django 4.1.4 on 2023-03-24 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_nearbyplaces_other_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherInfoPlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('distance', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('transport_mode', models.CharField(max_length=255)),
                ('drop_off_point_public_transport', models.CharField(max_length=255)),
                ('drop_off_point_private_transport', models.CharField(max_length=255)),
                ('trail_length_public_transport', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('trail_length_private_transport', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
            ],
        ),
        migrations.AlterField(
            model_name='nearbyplaces',
            name='other_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.otherinfoplaces'),
        ),
    ]
