# Generated by Django 4.1.4 on 2023-03-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_otherinfoplaces_alter_nearbyplaces_other_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='latitude',
            field=models.DecimalField(decimal_places=18, default=0.0, max_digits=30),
        ),
        migrations.AddField(
            model_name='listings',
            name='longitude',
            field=models.DecimalField(decimal_places=18, default=0.0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='otherinfoplaces',
            name='distance',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='otherinfoplaces',
            name='trail_length_private_transport',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='otherinfoplaces',
            name='trail_length_public_transport',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=7),
        ),
    ]
