# Generated by Django 4.1.4 on 2023-03-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0024_listings_latitude_listings_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='latitude',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='listings',
            name='longitude',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=30),
        ),
    ]
