# Generated by Django 4.1.4 on 2023-03-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0025_alter_listings_latitude_alter_listings_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='latitude',
            field=models.DecimalField(decimal_places=14, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='listings',
            name='longitude',
            field=models.DecimalField(decimal_places=14, default=0.0, max_digits=30),
        ),
    ]
