# Generated by Django 4.1.4 on 2023-03-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0026_alter_listings_latitude_alter_listings_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='place_id',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
