# Generated by Django 4.1.4 on 2023-03-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0027_listings_place_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='price_per_night',
            field=models.IntegerField(),
        ),
    ]
