# Generated by Django 4.1.4 on 2023-03-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0030_alter_listings_place_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='place_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
