# Generated by Django 4.1.4 on 2023-03-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0031_alter_listings_place_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/testimg/')),
            ],
        ),
    ]
