# Generated by Django 4.1.4 on 2023-03-31 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0032_testimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimg',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/testimg/%(name)s/'),
        ),
    ]
