# Generated by Django 4.1.4 on 2023-03-31 06:22

from django.db import migrations, models
import listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0035_alter_testimg_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photogallery',
            name='image',
            field=models.ImageField(blank=True, upload_to=listings.models.get_upload_path),
        ),
    ]
