# Generated by Django 4.1.4 on 2023-04-03 12:03

from django.db import migrations, models
import listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0037_remove_listings_thumb_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photogallery',
            name='image',
            field=models.ImageField(blank=True, upload_to=listings.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='thumbimages',
            name='url1',
            field=models.ImageField(blank=True, upload_to=listings.models.ThumbImages.get_thumb_upload_path),
        ),
        migrations.AlterField(
            model_name='thumbimages',
            name='url2',
            field=models.ImageField(blank=True, upload_to=listings.models.ThumbImages.get_thumb_upload_path),
        ),
        migrations.AlterField(
            model_name='thumbimages',
            name='url3',
            field=models.ImageField(blank=True, upload_to=listings.models.ThumbImages.get_thumb_upload_path),
        ),
        migrations.AlterField(
            model_name='thumbimages',
            name='url4',
            field=models.ImageField(blank=True, upload_to=listings.models.ThumbImages.get_thumb_upload_path),
        ),
        migrations.AlterField(
            model_name='thumbimages',
            name='url5',
            field=models.ImageField(blank=True, upload_to=listings.models.ThumbImages.get_thumb_upload_path),
        ),
    ]
