# Generated by Django 4.1.4 on 2023-04-03 12:30

from django.db import migrations, models
import django.db.models.deletion
import listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0038_alter_photogallery_image_alter_thumbimages_url1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thumbimages',
            old_name='url1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='thumbimages',
            name='url2',
        ),
        migrations.RemoveField(
            model_name='thumbimages',
            name='url3',
        ),
        migrations.RemoveField(
            model_name='thumbimages',
            name='url4',
        ),
        migrations.RemoveField(
            model_name='thumbimages',
            name='url5',
        ),
        migrations.AddField(
            model_name='thumbimages',
            name='caption',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='image',
            field=models.ImageField(blank=True, upload_to=listings.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='thumbimages',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='listings.listings'),
        ),
    ]
