# Generated by Django 4.1.4 on 2023-04-03 13:02

from django.db import migrations, models
import django.db.models.deletion
import listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0039_rename_url1_thumbimages_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thumbimages',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='thumbimages',
            name='image',
        ),
        migrations.RemoveField(
            model_name='thumbimages',
            name='listing',
        ),
        migrations.AddField(
            model_name='listings',
            name='thumb_images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.thumbimages'),
        ),
        migrations.AddField(
            model_name='thumbimages',
            name='listing_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='thumbimages',
            name='url1',
            field=models.ImageField(null=True, upload_to=listings.models.ThumbImages.get_thumb_upload_path),
        ),
        migrations.AddField(
            model_name='thumbimages',
            name='url2',
            field=models.ImageField(null=True, upload_to=listings.models.ThumbImages.get_thumb_upload_path),
        ),
        migrations.AddField(
            model_name='thumbimages',
            name='url3',
            field=models.ImageField(null=True, upload_to=listings.models.ThumbImages.get_thumb_upload_path),
        ),
        migrations.AddField(
            model_name='thumbimages',
            name='url4',
            field=models.ImageField(null=True, upload_to=listings.models.ThumbImages.get_thumb_upload_path),
        ),
        migrations.AddField(
            model_name='thumbimages',
            name='url5',
            field=models.ImageField(null=True, upload_to=listings.models.ThumbImages.get_thumb_upload_path),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='image',
            field=models.ImageField(blank=True, upload_to=listings.models.get_upload_path),
        ),
    ]
