# Generated by Django 4.1.4 on 2023-04-04 10:40

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0040_remove_thumbimages_caption_remove_thumbimages_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='description',
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='image',
            field=models.ImageField(blank=True, upload_to=listings.models.PhotoGallery.get_upload_path),
        ),
        migrations.CreateModel(
            name='ListingDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='listings.listings')),
            ],
        ),
    ]
