# Generated by Django 4.1.4 on 2023-04-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0041_remove_listings_description_alter_photogallery_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingdescription',
            old_name='description',
            new_name='complete_description',
        ),
        migrations.AddField(
            model_name='listingdescription',
            name='thumb_description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
