# Generated by Django 4.1.4 on 2023-04-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0042_rename_description_listingdescription_complete_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingdescription',
            name='thumb_description',
            field=models.TextField(max_length=200),
        ),
    ]
