# Generated by Django 4.1.4 on 2023-04-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0043_alter_listingdescription_thumb_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingdescription',
            name='thumb_description',
        ),
        migrations.AddField(
            model_name='listings',
            name='thumb_description',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
