# Generated by Django 4.1.4 on 2023-04-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0044_remove_listingdescription_thumb_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='thumb_description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
