# Generated by Django 4.1.4 on 2023-04-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0045_alter_listings_thumb_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressGeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lang', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
