# Generated by Django 4.1.4 on 2023-04-08 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0048_alter_photogallery_caption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photogallery',
            old_name='caption',
            new_name='photo_category',
        ),
    ]
