# Generated by Django 4.1.4 on 2023-04-09 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0049_rename_caption_photogallery_photo_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='thumb_images',
        ),
        migrations.RemoveField(
            model_name='thumbimages',
            name='listing_name',
        ),
        migrations.AddField(
            model_name='thumbimages',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumb_images', to='listings.listings'),
        ),
    ]
