# Generated by Django 4.1.4 on 2023-04-09 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0053_alter_thumbimages_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thingstoknow',
            name='name',
        ),
        migrations.AddField(
            model_name='thingstoknow',
            name='listing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='things_to_know', to='listings.listings'),
        ),
    ]
