# Generated by Django 4.1.4 on 2023-04-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0054_remove_thingstoknow_name_thingstoknow_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/host/dp'),
        ),
    ]
