# Generated by Django 4.1.4 on 2023-04-13 11:21

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0057_alter_listings_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingdescription',
            old_name='complete_description',
            new_name='about',
        ),
        migrations.AddField(
            model_name='listingdescription',
            name='layout',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listingdescription',
            name='location',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listingdescription',
            name='listing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lisitng_description', to='listings.listings'),
        ),
    ]
