# Generated by Django 4.1.4 on 2023-04-28 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0058_rename_complete_description_listingdescription_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenities',
            name='amenity_category',
            field=models.CharField(choices=[('bathroom', 'Bathroom'), ('kitchen', 'Kitchen'), ('bedroom and laundry', 'Bedroom and Laundry'), ('heating and cooling', 'Heating and Cooling'), ('internet and office', 'Internet and Office'), ('kitchen and dining', 'Kitchen and Dining'), ('parking and facilities', 'Parking and Facilities'), ('home safety', 'Home Safety'), ('services', 'Services'), ('other', 'Other')], default='other', max_length=40),
        ),
        migrations.AddField(
            model_name='amenities',
            name='amenity_description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='listingdescription',
            name='listing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_description', to='listings.listings'),
        ),
    ]
