# Generated by Django 4.1.4 on 2023-04-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0059_amenities_amenity_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities',
            name='amenity_category',
            field=models.CharField(choices=[('bathroom', 'Bathroom'), ('outooor', 'Outdoor'), ('bedroom and laundry', 'Bedroom and Laundry'), ('heating and cooling', 'Heating and Cooling'), ('internet and office', 'Internet and Office'), ('kitchen and dining', 'Kitchen and Dining'), ('parking and facilities', 'Parking and Facilities'), ('home safety', 'Home Safety'), ('services', 'Services'), ('other', 'Other')], default='other', max_length=40),
        ),
    ]
